//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46.101.242.170")]
        public string IPSSH {
            get {
                return ((string)(this["IPSSH"]));
            }
            set {
                this["IPSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string LoginSSH {
            get {
                return ((string)(this["LoginSSH"]));
            }
            set {
                this["LoginSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KJLE3t")]
        public string PasswordSSH {
            get {
                return ((string)(this["PasswordSSH"]));
            }
            set {
                this["PasswordSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public uint PortSSH {
            get {
                return ((uint)(this["PortSSH"]));
            }
            set {
                this["PortSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToGDBFolder {
            get {
                return ((string)(this["PathToGDBFolder"]));
            }
            set {
                this["PathToGDBFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46.101.242.170")]
        public string IPDataBasePostrgeSQL {
            get {
                return ((string)(this["IPDataBasePostrgeSQL"]));
            }
            set {
                this["IPDataBasePostrgeSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giscuit")]
        public string LoginDataBasePostgreSQL {
            get {
                return ((string)(this["LoginDataBasePostgreSQL"]));
            }
            set {
                this["LoginDataBasePostgreSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("igeoview")]
        public string PasswordDataBasePostgreSQL {
            get {
                return ((string)(this["PasswordDataBasePostgreSQL"]));
            }
            set {
                this["PasswordDataBasePostgreSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giscuit")]
        public string NameDataBasePostgreSQL {
            get {
                return ((string)(this["NameDataBasePostgreSQL"]));
            }
            set {
                this["NameDataBasePostgreSQL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("93, 90")]
        public global::System.Drawing.Size SizeOfButtonMenu {
            get {
                return ((global::System.Drawing.Size)(this["SizeOfButtonMenu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9pt, style=Bold")]
        public global::System.Drawing.Font FontButtonMenu {
            get {
                return ((global::System.Drawing.Font)(this["FontButtonMenu"]));
            }
        }
    }
}
