//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giscuit")]
        public string LoginSSH {
            get {
                return ((string)(this["LoginSSH"]));
            }
            set {
                this["LoginSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public uint PortSSH {
            get {
                return ((uint)(this["PortSSH"]));
            }
            set {
                this["PortSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToGDBFolder {
            get {
                return ((string)(this["PathToGDBFolder"]));
            }
            set {
                this["PathToGDBFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giscuit")]
        public string NameDataBasePostgreSQL {
            get {
                return ((string)(this["NameDataBasePostgreSQL"]));
            }
            set {
                this["NameDataBasePostgreSQL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI Light, 9pt")]
        public global::System.Drawing.Font FontButtonMenu {
            get {
                return ((global::System.Drawing.Font)(this["FontButtonMenu"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.115")]
        public string IPSSH {
            get {
                return ((string)(this["IPSSH"]));
            }
            set {
                this["IPSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giscuit")]
        public string PasswordSSH {
            get {
                return ((string)(this["PasswordSSH"]));
            }
            set {
                this["PasswordSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string IPDataBasePostrgeSQL {
            get {
                return ((string)(this["IPDataBasePostrgeSQL"]));
            }
            set {
                this["IPDataBasePostrgeSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Arcgis2PostgisWGS84 {
            get {
                return ((bool)(this["Arcgis2PostgisWGS84"]));
            }
            set {
                this["Arcgis2PostgisWGS84"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Postgis2ArcgisEPSG2039 {
            get {
                return ((bool)(this["Postgis2ArcgisEPSG2039"]));
            }
            set {
                this["Postgis2ArcgisEPSG2039"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string pgrowslimit {
            get {
                return ((string)(this["pgrowslimit"]));
            }
            set {
                this["pgrowslimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogMessage {
            get {
                return ((bool)(this["LogMessage"]));
            }
            set {
                this["LogMessage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 90")]
        public global::System.Drawing.Size SizeOfButtonMenu {
            get {
                return ((global::System.Drawing.Size)(this["SizeOfButtonMenu"]));
            }
        }
    }
}
